# This workflow will build a Java project with Gradle.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
     - name: Copy bot token
       run: cp -f ~/BotToken.java ~/actions-runner/_work/SlaveBot/SlaveBot/src/main/java/bot/slave
     - name: Copy resources
       run: cp -f ~/actions-runner/_work/SlaveBot/SlaveBot/resources/Jokes.txt ~/actions-runner/_work/SlaveBot/SlaveBot/build/libs/resources
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
     - name: Clean with Gradle
       run: ./gradlew clean
     - name: Build with Gradle
       run: ./gradlew shadowJar
#     - name: Run SlaveBot
#       run: java -jar ~/actions-runner/_work/SlaveBot/SlaveBot/build/libs/SlaveBot.jar
